In [19]:
import numpy as np

### Working with list

In [22]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
a + b # Adds the element pairs in b to a
a * b # Not allowed
np.dot(a, b) # Numpy allows only type of ndarray. Use np.ndarray() to initialize

TypeError: can't multiply sequence by non-int of type 'list'

### Working with numpy

In [23]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])

#### numpy matrix multiplication

In [24]:
np.dot(a,b) # This will do matrix multiplication if a and b are 2-D or more dimensions

array([[4, 1],
       [2, 2]])

In [28]:
a = np.array([1, 1])
b = np.array([2, 2])
np.dot(a, b) # This will do a vector dot product creating a scalar output if a and b are of 1-D size

4

In [29]:
a = np.array([1, 1]).transpose()
b = np.array([2, 2]).transpose()
np.dot(a, b)

4

In [31]:
a = [1, 1]
b = [2, 2]
np.dot(a, b) # This works too !

4

##### numpy elementwise multiplication

In [33]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
np.multiply(a, b)

array([[4, 0],
       [0, 2]])

##### Element wise multiplication without numpy

In [36]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
a*b

array([[4, 0],
       [0, 2]])

In [ ]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2], [3, 3]])
np.dot(a, b) # Fails if dimensions don't match

### Broadcasting

In [37]:
a = np.array([[1, 0], [0, 1]])
b = 5
a + b # Converts b to 2 x 2 so that it can add to a then does elementwise add

array([[6, 5],
       [5, 6]])

In [38]:
a = np.array([[1, 1], [1, 1]])
b = np.array([2, 3]).transpose()
a * b # Converts b to 2 * 2 by repeating the column then does elementwise multiplication

array([[2, 3],
       [2, 3]])

In [39]:
a = np.array([[16, 8], [4, 2]])
b = np.array([2, 2])
a/b # Repeats b row to make it 2 * 2 and then does elementwise divide

array([[8., 4.],
       [2., 1.]])